[phases.setup]
nixPkgs = ["nodejs_24", "npm-9_x", "openssl"]

[phases.build]
cmds = ["npm install", "npm run db:generate"]

[start]
cmd = "npm run db:migrate:deploy && npm run start -w @web3cash/api"

[variables]
NODE_ENV = "production"
