/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface Web3CashEscrowV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "attestor"
      | "campaigns"
      | "claim"
      | "claimed"
      | "createCampaign"
      | "deactivateCampaign"
      | "emergencyWithdraw"
      | "fundCampaign"
      | "fundPlatformReserve"
      | "getAvailableFunds"
      | "getCampaign"
      | "owner"
      | "platformReserve"
      | "renounceOwnership"
      | "setAttestor"
      | "transferOwnership"
      | "withdrawCampaignFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestorUpdated"
      | "CampaignCreated"
      | "CampaignDeactivated"
      | "CampaignFunded"
      | "CampaignWithdrawn"
      | "Claimed"
      | "OwnershipTransferred"
      | "PlatformReserveFunded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "attestor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "claimed", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateCampaign",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundCampaign",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundPlatformReserve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableFunds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAttestor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCampaignFunds",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "attestor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundPlatformReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCampaignFunds",
    data: BytesLike
  ): Result;
}

export namespace AttestorUpdatedEvent {
  export type InputTuple = [oldAttestor: AddressLike, newAttestor: AddressLike];
  export type OutputTuple = [oldAttestor: string, newAttestor: string];
  export interface OutputObject {
    oldAttestor: string;
    newAttestor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [campaignId: BytesLike, creator: AddressLike];
  export type OutputTuple = [campaignId: string, creator: string];
  export interface OutputObject {
    campaignId: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignDeactivatedEvent {
  export type InputTuple = [campaignId: BytesLike];
  export type OutputTuple = [campaignId: string];
  export interface OutputObject {
    campaignId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFundedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    funder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    funder: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignWithdrawnEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    creator: string,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    claimId: BytesLike
  ];
  export type OutputTuple = [
    campaignId: string,
    recipient: string,
    amount: bigint,
    claimId: string
  ];
  export interface OutputObject {
    campaignId: string;
    recipient: string;
    amount: bigint;
    claimId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformReserveFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Web3CashEscrowV2 extends BaseContract {
  connect(runner?: ContractRunner | null): Web3CashEscrowV2;
  waitForDeployment(): Promise<this>;

  interface: Web3CashEscrowV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  attestor: TypedContractMethod<[], [string], "view">;

  campaigns: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        creator: string;
        balance: bigint;
        spent: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  claim: TypedContractMethod<
    [
      campaignId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      claimId: BytesLike,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  createCampaign: TypedContractMethod<
    [campaignId: BytesLike],
    [void],
    "nonpayable"
  >;

  deactivateCampaign: TypedContractMethod<
    [campaignId: BytesLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundCampaign: TypedContractMethod<
    [campaignId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundPlatformReserve: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAvailableFunds: TypedContractMethod<
    [campaignId: BytesLike],
    [bigint],
    "view"
  >;

  getCampaign: TypedContractMethod<
    [campaignId: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        creator: string;
        balance: bigint;
        spent: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformReserve: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAttestor: TypedContractMethod<
    [_attestor: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawCampaignFunds: TypedContractMethod<
    [campaignId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "attestor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        creator: string;
        balance: bigint;
        spent: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      campaignId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      claimId: BytesLike,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<[campaignId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateCampaign"
  ): TypedContractMethod<[campaignId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundCampaign"
  ): TypedContractMethod<
    [campaignId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundPlatformReserve"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAvailableFunds"
  ): TypedContractMethod<[campaignId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        creator: string;
        balance: bigint;
        spent: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAttestor"
  ): TypedContractMethod<[_attestor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawCampaignFunds"
  ): TypedContractMethod<
    [campaignId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AttestorUpdated"
  ): TypedContractEvent<
    AttestorUpdatedEvent.InputTuple,
    AttestorUpdatedEvent.OutputTuple,
    AttestorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignDeactivated"
  ): TypedContractEvent<
    CampaignDeactivatedEvent.InputTuple,
    CampaignDeactivatedEvent.OutputTuple,
    CampaignDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFunded"
  ): TypedContractEvent<
    CampaignFundedEvent.InputTuple,
    CampaignFundedEvent.OutputTuple,
    CampaignFundedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignWithdrawn"
  ): TypedContractEvent<
    CampaignWithdrawnEvent.InputTuple,
    CampaignWithdrawnEvent.OutputTuple,
    CampaignWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformReserveFunded"
  ): TypedContractEvent<
    PlatformReserveFundedEvent.InputTuple,
    PlatformReserveFundedEvent.OutputTuple,
    PlatformReserveFundedEvent.OutputObject
  >;

  filters: {
    "AttestorUpdated(address,address)": TypedContractEvent<
      AttestorUpdatedEvent.InputTuple,
      AttestorUpdatedEvent.OutputTuple,
      AttestorUpdatedEvent.OutputObject
    >;
    AttestorUpdated: TypedContractEvent<
      AttestorUpdatedEvent.InputTuple,
      AttestorUpdatedEvent.OutputTuple,
      AttestorUpdatedEvent.OutputObject
    >;

    "CampaignCreated(bytes32,address)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignDeactivated(bytes32)": TypedContractEvent<
      CampaignDeactivatedEvent.InputTuple,
      CampaignDeactivatedEvent.OutputTuple,
      CampaignDeactivatedEvent.OutputObject
    >;
    CampaignDeactivated: TypedContractEvent<
      CampaignDeactivatedEvent.InputTuple,
      CampaignDeactivatedEvent.OutputTuple,
      CampaignDeactivatedEvent.OutputObject
    >;

    "CampaignFunded(bytes32,address,uint256)": TypedContractEvent<
      CampaignFundedEvent.InputTuple,
      CampaignFundedEvent.OutputTuple,
      CampaignFundedEvent.OutputObject
    >;
    CampaignFunded: TypedContractEvent<
      CampaignFundedEvent.InputTuple,
      CampaignFundedEvent.OutputTuple,
      CampaignFundedEvent.OutputObject
    >;

    "CampaignWithdrawn(bytes32,address,uint256)": TypedContractEvent<
      CampaignWithdrawnEvent.InputTuple,
      CampaignWithdrawnEvent.OutputTuple,
      CampaignWithdrawnEvent.OutputObject
    >;
    CampaignWithdrawn: TypedContractEvent<
      CampaignWithdrawnEvent.InputTuple,
      CampaignWithdrawnEvent.OutputTuple,
      CampaignWithdrawnEvent.OutputObject
    >;

    "Claimed(bytes32,address,uint256,bytes32)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformReserveFunded(address,uint256)": TypedContractEvent<
      PlatformReserveFundedEvent.InputTuple,
      PlatformReserveFundedEvent.OutputTuple,
      PlatformReserveFundedEvent.OutputObject
    >;
    PlatformReserveFunded: TypedContractEvent<
      PlatformReserveFundedEvent.InputTuple,
      PlatformReserveFundedEvent.OutputTuple,
      PlatformReserveFundedEvent.OutputObject
    >;
  };
}
